# Generated by Django 5.1.4 on 2024-12-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
    ]
